development:
#  identity_map_enabled: true
#  logger: true
#  host: localhost
#  database: trust_exchange_development
  uri: "mongodb://:@127.0.0.1:27017/trust_exchange_development"

test:
  identity_map_enabled: true
  logger: true
  host: localhost
  database: trust_exchange_test

# set these environment variables on your prod server
production:
  identity_map_enabled: true
  logger: true
  uri: <%= ENV['MONGOHQ_URL'] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
