#!/usr/bin/env ruby
# This command will launch the mongo console connected to the production database
# on Heroku

require File.expand_path('../../lib/heroku_utils', __FILE__)

mongo_credentials = HerokuUtils.get_mongo_production_credentials
puts "***WARNING -- you are connected to the live production database***"
puts "***WITH GREAT POWERS COME GREAT RESPONSIBILITIES***"
system("mongo #{mongo_credentials[:host_port_db]} -u #{mongo_credentials[:username]} -p #{mongo_credentials[:password]}")
